"""
main.py - Command-Line Interface (CLI)
-------------------------------------
This file serves as the entry point, the CLI, for the Flight Management System. The user 
interacts with this file: it handles input and orchestrates calls to functions in other 
files (namely dbOperations.py) which are necessary to carry out queries on the data, 
such as making changes to the database and getting information from the database.

Press play to run the script or type 'python main.py' into the terminal to start the 
application.
"""
import sys
import time
from dbOperations import flightAttributeList, addFlight, viewFlightsByCriteria
#import sqlite3

def main():
    print("\nHello, welcome to the flight management system.")
    time.sleep(2)
    print("\nPlease enter select your role number:")
    time.sleep(1.5)
    print("1. Cat Walking Over Keyboard")
    print("2. Flight Attendant")
    print("3. Database Manager")
    time.sleep(1.5)
    
    userRole = input("\nEnter role number: ").strip() # strip() to remove leading and trailing spaces
    time.sleep(1.5)
    
    if userRole == "1":
        catRole()
    elif userRole == "2":
        flightAttendantActions() #view/read only
    elif userRole == "3":
        databaseManagerActions() #full CRUD permissions
    else:
        print("Invalid role. Restarting.")
        time.sleep(3)
        main()

#================•UTILITY DATA & FUNCTIONS•================
def handleUserReset():
    print("\nEnter 'Exit' to leave the session, enter 'Return' to start again.")
    userInput = input("Enter: ").strip().lower() #lower so that it isn't case sensitive
    time.sleep(2)
    if userInput == 'exit':
        sys.exit()
    else:
        main()
        
"""
Dictionary for field guidance
"""
attributeGuidance = {
    "destination": {
        "destinationID": "(PK. 3 character airport name abbreviation)",
        "destinationName": "(Airport name)"
    },
    "terminal": {
        "terminalID": "(PK. Terminal name abbreviation)",
        "terminalName": "(Optional. Full terminal name)"
    },
    "pilot": {
        "pilotID": "PK. Autogenerated by system", #auto
        "pilotName": "",
        "email": "",#enfoce "@domain"
        "dob": "(YYYY-MM-DD)",
        "isCaptainQualified": "(0 for No, 1 for Yes)",
        "isFirstOfficerQualified": "(0 for No, 1 for Yes)"
    },
    "flight": {
        "flightID": "(Flight Number, Part 1 of PK)",
        "scheduledDepartureDateTime": "(YYYY-MM-DD HH:MM:SS, Part 2 of PK)",
        "flightStatus": "(Allowable values: Scheduled, In-air, Landed, Cancelled)",
        "captainID": "(Optional. Must exist in pilot table)",
        "firstOfficerID": "(Optional. Must exist in pilot table)",
        "arrivalDestinationID": "(3 letter airport code. Must exist in destination table)",
        "departureDestinationID": "(3 letter airport code. Must exist in destination table)",
        "diversionDestinationID": "(Optional. 3 letter airport code. Must exist in destination table)",
        "departureTerminalID": "(Must exist in terminal table)",
        "arrivalTerminalID": "(Optional. Must exist in terminal table)",
        "diversionTerminalID": "(Optional. Must exist in terminal table)",
        "scheduledArrivalDateTime": "(YYYY-MM-DD HH:MM:SS)",
        "actualArrivalDateTime": "(Optional. YYYY-MM-DD HH:MM:SS)",
        "actualDepartureDateTime": "(Optional. YYYY-MM-DD HH:MM:SS)",
    }
}

"""
Reusable function to get user input for any table
"""
def getUserInput(tableName, attributeList):
    print(f"Entering details for {tableName} table...")
    collectedData = []
    
    inputGuidance = attributeGuidance.get(tableName, {})
    
    for attribute in attributeList:
        #pilotID is an autoincrement ID. Don't want user input for this
        if attribute == "pilotID":
            print(f"{attribute}: No entry needed. Auto-generated")
            continue #skip input call for this attribute
        guidance = inputGuidance.get(attribute, "")
        val = input(f"Enter {attribute} {guidance}: ").strip()
        
        #Check for missing mandatory field. If error, ask user to re-enter value
        if val == "" and ("PK" in guidance or "Optional" not in guidance):
            while val == "":
                print(f"ERROR: {attribute} is required.")
                val = input(f"Enter {attribute} {guidance}: ").strip()
            
        collectedData.append(val if val != "" else None)
        
    return tuple(collectedData)

"""
Option 3
"""
def getFlightsByCriteria():
    print("\nDo you want to view flight by...")
    time.sleep(2)
    print("1. By Flight Status")
    print("2. Arrival Destination")
    time.sleep(2)
    
    userChoice = input("Enter the number of your selection: ").strip()
    
    print("\nWhich information would you like to see? Provide a comma seperated list.")
    time.sleep(1)
    print(f"The available columns are: {', '.join(flightAttributeList)}")
    time.sleep(2)
    attributeInput = input("Enter columns (or 'all'): ").strip().lower()
    
    selectedAttributes = [a.strip() for a in attributeInput.split(",")]
    
    if userChoice == "1":
        search = getUserInput("flight", ["flightStatus"])
        #pass tuple to function in dbOperations
        viewFlightsByCriteria("flightStatus", search, selectedAttributes)
        
    elif userChoice == "2":
        search = getUserInput("flight", ["arrivalDestinationID"])
        viewFlightsByCriteria("arrivalDestination", search, selectedAttributes)
    

"""
Option 5: Get flights without full crew
"""
def getFlightsWithoutCrew():
    print("\nSearching for Scheduled Flights without a Pilot assigned...")

    selectedAttributes = [
        "flightID", "scheduledDepartureDateTime", "flightStatus", "captainID", "firstOfficerID", "arrivalDestinationID", "departureDestinationID"
        ]
    viewFlightsByCriteria("unassigned", (), selectedAttributes) #() because no ? placeholder


# """
# Prompts user to enter values for new flight
# Returns tuples (attributeName, value)
# """       
# def getFlightUserInput():
#     print("\Please enter flight details. Optional fields can be left blank.")
#     collectedData = []
    
#     for attribute in flightAttributeList:
#         val = input(f"Enter {attribute} ").strip()
#         collectedData.append(val if val != "" else None)
    
#     return tuple(collectedData)

#================•ROLE MENUS•================
def catRole():
    print("\nSorry, you don't have access to the data.")
    time.sleep(1.5)
    

#The Flight Attended is only able to view (SELECT) data.
def flightAttendantActions():
    print("\nHello, Flight Attendant")    
    time.sleep(2)
    print("\nSorry, your profile hasn't been set up yet.")
    time.sleep(1.5)
    handleUserReset()
    # print("\nWhat would you like to do? Please select an action from the menu:")
    # time.sleep(2)
    # print("View Flights by Criteria")

#The Database Manager is able to perform all CRUD operations.
def databaseManagerActions():
    while True:
        print("\nHello, Database Manager")    
        time.sleep(2)  
        print("\nWhat would you like to do? Please review the below actions:")
        time.sleep(2)
        print("1. View Data")                   #read   - SELECT
        print("2. Add a New Flight")            #create - INSERT
        print("3. View Flights by Criteria")    #read   - SELECT
        print("4. Update Flight Information")   #update - UPDATE        #incl update flight status
        print("5. View Flights Without Full Crew")
        print("6. View Pilot Schedule") #Include View Available Pilots
        print("7. View Available Pilots")
        print("8. Assign Pilot to Flight") #Include View Available Pilots
        print("9. View/Update Destination Information")
        print("10. Add a New Pilot")
        print("11. Delete a Pilot")             #delete - DELETE
        print("12. View The Most Popular Airport") #a) of all time, b) by single date, c) by date range
        print("13. View Number of Flights Pilot Are Assigned To)") #Col0=Name, Col1=Captain, Col2=FO, Col3=Both
        print("14. View Average Delayed Arrival")
        print("15. View Number of Flights Landed on Date") #i.e. 
        print("16. Leave This Session")
        
        time.sleep(2)
        userChoice = input("\nEnter your selections number: ").strip()
        if userChoice == '1':
            # viewTable(userInput)
            pass
        elif userChoice == '2':
            userInput = getUserInput("flight", flightAttributeList)
            addFlight(userInput)
        elif userChoice == '3':
            getFlightsByCriteria()
        elif userChoice == '4':
            print("Undefined")
            pass
        elif userChoice == '5':
            getFlightsWithoutCrew()
        elif userChoice == '6':
            print("Undefined")
            pass
        elif userChoice == '7':
            print("Undefined")
            pass
        elif userChoice == '8':
            print("Undefined")
            pass
        elif userChoice == '9':
            print("Undefined")
            pass
        elif userChoice == '10':
            print("Undefined")
            pass
        elif userChoice == '11':
            print("Undefined")
            pass
        elif userChoice == '12':
            print("Undefined")
            pass       
        elif userChoice == '13':
            break
        else:
            print("Invalid selection")
            handleUserReset()
            
#================•FUNCTIONS•================


if __name__ == "__main__":
    main()
